### ISSUE TITLE
PNGExporter actually exports GIF files

### ISSUE THREAD

**Issue by EricDuminil** [antscloud/fretboardgtr#25]
**Describe the bug**
When exporting a fretboard with format 'png', a gif file (possibly with extension '.png') is written instead.

**To Reproduce**
`fretboard.export("my_fretboard.png", format="png")`

**Expected behavior**
A PNG file should be written.

[`reportlab.graphics.renderPM.drawToFile`](https://github.com/eduardocereto/reportlab/blob/master/src/reportlab/graphics/renderPM.py#L657C5-L657C15) seems to default to GIF. Specifying `fmt='PNG'` in PNGExporter should fix the problem.

**Comment by antscloud** [comment]
Nice catch, thank you ! 
Either the API of renderPM has changed or this is a miss from the refactoring

**Comment by antscloud** [comment]
You should be good to go with a fresh install 

```sh
pip install fretboardgtr --upgrade
```

**Comment by EricDuminil** [comment]
Thanks for the quick feedback! It works fine now.
