### ISSUE TITLE
Support Tenor Banjo Fret Diagrams

### ISSUE THREAD

**Issue by jgarte** [antscloud/fretboardgtr#26]
**Is your feature request related to a problem? Please describe.**

I'd like to have built-in support for tenor banjo. The tuning is C G D A.

**Describe the solution you'd like**

I'd like to be able to generate scales and chords for the tenor banjo fretboard.

**Additional context**

https://en.wikipedia.org/wiki/Banjo#Tenor_banjo

**Comment by antscloud** [comment]
Hi, you can already do this by specifying the tuning in the Fretboard object 
```python
fretboard = FretBoard( tuning=["C', "G", "D", "A"])
...
```

**Comment by jgarte** [comment]
Nice! TIL
