### ISSUE TITLE
VerticalFretboad regression

### ISSUE THREAD

**Issue by brusand** [antscloud/fretboardgtr#28]
**Describe the bug**
don t display the chord as Fretboard
![chords_fretboard](https://github.com/antscloud/fretboardgtr/assets/1648561/0ed7a4ba-c628-41b6-9c4b-9fecf202c08c)

**To Reproduce**
config = {
        "general": {
            "first_fret": 0,
            "last_fret": 16,
            "fret_width": 50,
            "show_note_name": True,
            "show_degree_name": False,
        }
    }
    fretboard_config = FretBoardConfig.from_dict(config)
    fretboard = VerticalFretBoard(config=fretboard_config)
    c_major =  [0, 3, 2, 0, 1, 0]

    fretboard.add_fingering(c_major)
    fretboard.export("chords_fretboard.svg", format="svg")

**Expected behavior**
![chords_fretboard](https://github.com/antscloud/fretboardgtr/assets/1648561/210b5e00-8923-48b4-a774-76e8138d66ae)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by antscloud** [comment]
Hi, thank you for the issue 
With the latest version, the following code works as expected : 
```python
from fretboardgtr.fretboard import FretBoard, FretBoardConfig
from typing import List

config = {
    "general": {
        "first_fret": 0,
        "last_fret": 16,
        "fret_width": 50,
        "show_note_name": True,
        "show_degree_name": False,
    }
}
fretboard_config = FretBoardConfig.from_dict(config)
fretboard = FretBoard(config=fretboard_config, vertical=True)
c_major: List[int | None] = [0, 3, 2, 0, 1, 0]
fretboard.add_fingering(c_major, root="C")
fretboard.export("chords_fretboard.svg", format="svg")
```

You may be using an old version because, `VerticalFretBoard` does not have the `add_fingering` on the latest version. Only FretBoard has it
